package report

import (
	"fmt"
	"html"
	"regexp"
	"strings"

	"github.com/linnea-bakshi/gha-doctor/internal/lint"
)

// HTMLMeta describes the shell around a rendered HTML report.
type HTMLMeta struct {
	Title    string // page title + heading, e.g. "gha-doctor — cli/cli"
	Subtitle string // e.g. "generated 2026-07-31 09:40 UTC · gha-doctor v0.25.0"
	Grade    string // optional health grade chip ("A+" … "F"); empty = no chip
	Points   int    // score shown next to the grade chip

	// Charts holds trusted, self-generated SVG snippets (see Charts())
	// rendered between the header and the report body. Never put
	// user-controlled markup here: it is written unescaped by design.
	Charts []string
}

// HTMLPage converts gha-doctor's own Markdown output into a self-contained
// HTML page (inline CSS, no scripts, no external assets). This is NOT a
// general-purpose Markdown converter: it handles exactly the constructs our
// renderers emit — headings, tables, ordered lists, blockquotes, fenced code,
// bold/italic/inline-code/links — and escapes everything else, so report
// content (job names, log lines) can never inject markup.
func HTMLPage(md string, meta HTMLMeta) []byte {
	var b strings.Builder
	b.WriteString("<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n")
	b.WriteString("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n")
	fmt.Fprintf(&b, "<title>%s</title>\n", html.EscapeString(meta.Title))
	b.WriteString("<style>\n" + htmlCSS + "</style>\n</head>\n<body>\n<main>\n")

	b.WriteString("<header>\n")
	fmt.Fprintf(&b, "<h1>%s", html.EscapeString(meta.Title))
	if meta.Grade != "" {
		fmt.Fprintf(&b, " <span class=\"grade\" style=\"background:%s\">%s · %d/100</span>",
			badgeColor(meta.Grade), html.EscapeString(meta.Grade), meta.Points)
	}
	b.WriteString("</h1>\n")
	if meta.Subtitle != "" {
		fmt.Fprintf(&b, "<p class=\"sub\">%s</p>\n", html.EscapeString(meta.Subtitle))
	}
	b.WriteString("</header>\n")

	for _, c := range meta.Charts {
		b.WriteString("<figure class=\"chart\">\n" + c + "\n</figure>\n")
	}

	writeHTMLBody(&b, md)

	b.WriteString("<footer>Generated by <a href=\"https://github.com/linnea-bakshi/gha-doctor\">gha-doctor</a>" +
		" — CI speed, cost, and reliability checkup for GitHub Actions." +
		" <a href=\"https://linnea-bakshi.github.io/gha-doctor/\">Docs</a></footer>\n")
	b.WriteString("</main>\n</body>\n</html>\n")
	return []byte(b.String())
}

// writeHTMLBody converts the markdown body line-by-line.
func writeHTMLBody(b *strings.Builder, md string) {
	lines := strings.Split(md, "\n")
	var para []string
	flushPara := func() {
		if len(para) == 0 {
			return
		}
		fmt.Fprintf(b, "<p>%s</p>\n", htmlInline(strings.Join(para, " ")))
		para = nil
	}
	for i := 0; i < len(lines); i++ {
		line := lines[i]
		switch {
		case strings.HasPrefix(line, "```"):
			flushPara()
			b.WriteString("<pre><code>")
			for i++; i < len(lines) && !strings.HasPrefix(lines[i], "```"); i++ {
				b.WriteString(html.EscapeString(lines[i]) + "\n")
			}
			b.WriteString("</code></pre>\n")
		case strings.HasPrefix(line, "### "):
			flushPara()
			fmt.Fprintf(b, "<h3>%s</h3>\n", htmlInline(strings.TrimPrefix(line, "### ")))
		case strings.HasPrefix(line, "## "):
			flushPara()
			fmt.Fprintf(b, "<h2>%s</h2>\n", htmlInline(strings.TrimPrefix(line, "## ")))
		case strings.HasPrefix(line, "> "):
			flushPara()
			b.WriteString("<blockquote>\n")
			for ; i < len(lines) && strings.HasPrefix(lines[i], "> "); i++ {
				fmt.Fprintf(b, "<p>%s</p>\n", htmlInline(strings.TrimPrefix(lines[i], "> ")))
			}
			i--
			b.WriteString("</blockquote>\n")
		case strings.HasPrefix(line, "|"):
			flushPara()
			var rows []string
			for ; i < len(lines) && strings.HasPrefix(lines[i], "|"); i++ {
				rows = append(rows, lines[i])
			}
			i--
			writeHTMLTable(b, rows)
		case htmlOLItem.MatchString(line):
			flushPara()
			b.WriteString("<ol>\n")
			for ; i < len(lines) && htmlOLItem.MatchString(lines[i]); i++ {
				fmt.Fprintf(b, "<li>%s</li>\n", htmlInline(htmlOLItem.ReplaceAllString(lines[i], "")))
			}
			i--
			b.WriteString("</ol>\n")
		case strings.HasPrefix(line, "- "):
			flushPara()
			b.WriteString("<ul>\n")
			for ; i < len(lines) && strings.HasPrefix(lines[i], "- "); i++ {
				fmt.Fprintf(b, "<li>%s</li>\n", htmlInline(strings.TrimPrefix(lines[i], "- ")))
			}
			i--
			b.WriteString("</ul>\n")
		case strings.TrimSpace(line) == "":
			flushPara()
		default:
			para = append(para, line)
		}
	}
	flushPara()
}

var htmlOLItem = regexp.MustCompile(`^\d+\. `)

// writeHTMLTable renders a block of `| … |` lines. The first row is the
// header; separator rows (all cells dashes) are skipped.
func writeHTMLTable(b *strings.Builder, rows []string) {
	b.WriteString("<table>\n")
	header := true
	for _, row := range rows {
		cells := splitTableRow(row)
		if isSeparatorRow(cells) {
			continue
		}
		tag := "td"
		if header {
			tag = "th"
		}
		b.WriteString("<tr>")
		for _, c := range cells {
			cls := ""
			switch strings.TrimSpace(c) {
			case "warn", "warning":
				cls = ` class="sev-warn"`
			case "info":
				cls = ` class="sev-info"`
			}
			fmt.Fprintf(b, "<%s%s>%s</%s>", tag, cls, htmlInline(c), tag)
		}
		b.WriteString("</tr>\n")
		if header {
			header = false
		}
	}
	b.WriteString("</table>\n")
}

// splitTableRow splits a markdown table row into cells, honoring the \|
// escape our renderers use for literal pipes in messages.
func splitTableRow(row string) []string {
	row = strings.TrimSpace(row)
	row = strings.TrimPrefix(row, "|")
	row = strings.TrimSuffix(row, "|")
	const esc = "\x00" // placeholder that never occurs in report text
	row = strings.ReplaceAll(row, `\|`, esc)
	parts := strings.Split(row, "|")
	for i := range parts {
		parts[i] = strings.TrimSpace(strings.ReplaceAll(parts[i], esc, "|"))
	}
	return parts
}

func isSeparatorRow(cells []string) bool {
	for _, c := range cells {
		c = strings.TrimSpace(c)
		if c == "" || strings.Trim(c, ":-") != "" {
			return false
		}
	}
	return true
}

var (
	htmlCode   = regexp.MustCompile("`([^`]+)`")
	htmlLink   = regexp.MustCompile(`\[([^\]]+)\]\((https?://[^)\s]+)\)`)
	htmlBold   = regexp.MustCompile(`\*\*(.+?)\*\*`)
	htmlItalic = regexp.MustCompile(`(^|\s)_([^_](?:[^_]*[^_\s])?)_($|[\s.,;:)])`)
	htmlRuleID = regexp.MustCompile(`\bD0\d\d\b`)
)

// htmlInline escapes a fragment and applies inline markdown: code spans,
// links, bold, italics, and rule-ID links to the docs site. Code spans are
// protected with placeholders so later passes can't touch their contents.
func htmlInline(s string) string {
	s = html.EscapeString(s)

	var protected []string
	s = htmlCode.ReplaceAllStringFunc(s, func(m string) string {
		inner := htmlCode.FindStringSubmatch(m)[1]
		protected = append(protected, "<code>"+ruleLink(inner)+"</code>")
		return fmt.Sprintf("\x00%d\x00", len(protected)-1)
	})

	s = htmlLink.ReplaceAllString(s, `<a href="$2">$1</a>`)
	s = htmlBold.ReplaceAllString(s, "<strong>$1</strong>")
	s = htmlItalic.ReplaceAllString(s, "$1<em>$2</em>$3")
	s = ruleLink(s)

	for i, p := range protected {
		s = strings.Replace(s, fmt.Sprintf("\x00%d\x00", i), p, 1)
	}
	return s
}

// ruleLink turns bare rule IDs (D001…) into links to their docs section,
// but only for rules that actually exist.
func ruleLink(s string) string {
	return htmlRuleID.ReplaceAllStringFunc(s, func(id string) string {
		m, ok := lint.RuleMeta[id]
		if !ok {
			return id
		}
		return fmt.Sprintf(`<a href="https://linnea-bakshi.github.io/gha-doctor/rules#%s-%s">%s</a>`,
			strings.ToLower(m.ID), strings.ToLower(m.Name), id)
	})
}

// htmlCSS is the whole stylesheet: GitHub-dark palette, no external fonts.
const htmlCSS = `
:root { color-scheme: dark; }
* { box-sizing: border-box; }
body { margin: 0; background: #0d1117; color: #e6edf3;
  font: 15px/1.55 -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif; }
main { max-width: 900px; margin: 0 auto; padding: 32px 24px 48px; }
header { border-bottom: 1px solid #30363d; margin-bottom: 20px; padding-bottom: 12px; }
h1 { font-size: 24px; margin: 0 0 4px; }
h2 { font-size: 20px; margin: 28px 0 10px; border-bottom: 1px solid #21262d; padding-bottom: 6px; }
h3 { font-size: 16px; margin: 22px 0 8px; }
.sub { color: #8b949e; margin: 0; font-size: 13px; }
.grade { display: inline-block; font-size: 13px; font-weight: 600; color: #fff;
  border-radius: 12px; padding: 2px 10px; vertical-align: middle; margin-left: 8px; }
p { margin: 8px 0; }
a { color: #58a6ff; text-decoration: none; }
a:hover { text-decoration: underline; }
code { background: #161b22; border: 1px solid #30363d; border-radius: 4px;
  padding: 1px 5px; font: 12.5px ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; }
code a { color: inherit; text-decoration: underline dotted; }
pre { background: #161b22; border: 1px solid #30363d; border-radius: 6px;
  padding: 12px; overflow-x: auto; }
pre code { background: none; border: none; padding: 0; display: block;
  font-size: 12.5px; line-height: 1.45; }
table { border-collapse: collapse; width: 100%; margin: 10px 0; font-size: 13.5px; }
th, td { border: 1px solid #30363d; padding: 5px 10px; text-align: left; }
th { background: #161b22; }
tr:nth-child(even) td { background: #0f141b; }
.sev-warn { color: #d29922; font-weight: 600; }
.sev-info { color: #58a6ff; }
blockquote { border-left: 3px solid #3fb950; margin: 12px 0; padding: 2px 14px;
  background: #12261e; border-radius: 0 6px 6px 0; }
blockquote p { margin: 6px 0; }
ol { padding-left: 24px; }
ol li { margin: 6px 0; }
em { color: #8b949e; }
figure.chart { margin: 18px 0; background: #0f141b; border: 1px solid #21262d;
  border-radius: 6px; padding: 10px 6px 4px; }
figure.chart svg { max-width: 100%; height: auto; display: block; }
footer { margin-top: 36px; border-top: 1px solid #30363d; padding-top: 12px;
  color: #8b949e; font-size: 13px; }
`
