#!/usr/bin/env python3
"""Emit docs/ubuntu-22-04.md: the ubuntu-22.04 retirement countdown page.

Usage: scripts/gen-runner-countdown.py CACHE_DIR > docs/ubuntu-22-04.md

CACHE_DIR is a state-of-actions.sh cache (per-repo --lint-only --json).
The page is a dated snapshot: regenerating with a fresh cache updates
the numbers and the date line together.
"""
import collections
import datetime
import glob
import json
import os
import sys

cache = sys.argv[1]
LABELS = ("ubuntu-22.04-arm", "ubuntu-22.04")  # arm first: prefix-safe matching

scanned = analyzable = 0
repo_jobs = collections.Counter()   # repo -> ubuntu-22.04* D020 findings (jobs)
repo_files = collections.defaultdict(set)
total_jobs = 0

for f in sorted(glob.glob(cache + "/*=*.json")):
    repo = os.path.basename(f)[:-5].replace("=", "/")
    d = json.load(open(f))
    scanned += 1
    if d.get("no_workflows") or d.get("error"):
        continue
    analyzable += 1
    for fd in d.get("findings") or []:
        if fd.get("rule") != "D020":
            continue
        msg = fd.get("message", "")
        if not any("`%s`" % l in msg for l in LABELS):
            continue
        repo_jobs[repo] += 1
        total_jobs += 1
        repo_files[repo].add(fd.get("file", ""))

if analyzable < 100:
    sys.exit("cache looks incomplete (%d analyzable repos) — refusing" % analyzable)

today = datetime.date.today().isoformat()
n_repos = len(repo_jobs)
n_files = sum(len(v) for v in repo_files.values())
top = repo_jobs.most_common(10)

W = sys.stdout.write
W(f"""# The ubuntu-22.04 countdown

**The `ubuntu-22.04` and `ubuntu-22.04-arm` hosted runners are being
retired.** GitHub announced the schedule in
[actions/runner-images#14254](https://github.com/actions/runner-images/issues/14254):

| date | what happens |
|------|--------------|
| **September 17, 2026** | deprecation begins — longer queue times during peak hours |
| **March 23 / 30, April 6 / 13, 2027** | scheduled failure brownouts — jobs that run during the windows **fail** |
| **April 17, 2027** | fully unsupported — jobs requesting the label stop running entirely |

(Dates from the announcement as of {today}; the issue is the source of
truth if GitHub adjusts the schedule.)

`ubuntu-latest` users are not affected — it has pointed at
`ubuntu-24.04` since late 2024. This page is about workflows that **pin**
the label.

## How many repos are still on it?

Snapshot of {today}, static lint of the default branch of the
{scanned} most-starred repos on GitHub ({analyzable} with analyzable
workflows — same population as the
[state of the top 250](state-of-actions.md) study):

- **{n_repos} of {analyzable} repos** still pin `ubuntu-22.04` somewhere
- **{total_jobs} jobs** across **{n_files} workflow files**

The busiest offenders:

| repo | jobs pinning ubuntu-22.04\\* | workflow files |
|------|------------------------------|----------------|
""")
for repo, jobs in top:
    W(f"| [{repo}](https://github.com/{repo}) | {jobs} | {len(repo_files[repo])} |\n")

W(f"""
(A "job" here is one D020 finding: one `runs-on:` label occurrence,
including labels reached through `${{{{ matrix.os }}}}` values. Counts are
what [`gha-doctor` rule D020](rules.md#d020-deprecatingrunnerlabel)
reports with `--lint-only` — no run history involved.)

## The one-command migration

`gha-doctor` flags every pinned `ubuntu-22.04`/`ubuntu-22.04-arm` label
(rule **D020**) and `--fix` rewrites them to `ubuntu-24.04` /
`ubuntu-24.04-arm` — a same-architecture, mechanical swap with an
unambiguous target:

```console
$ gha-doctor --diff              # preview the patch
$ gha-doctor --fix               # apply it
```

No checkout handy? Lint any repo remotely and apply the patch locally:

```console
$ gha-doctor --repo you/yourrepo --diff > bump.patch
$ git apply bump.patch           # in a clone
```

What `--fix` deliberately does **not** touch (you get a loud skip note
instead of a silent edit):

- labels reached through `${{{{ matrix.KEY }}}}` — the matrix value's text
  may be referenced in `if:`/`include:`/`exclude:` logic the linter
  can't see
- Windows and macOS labels — the target is a judgment call (see below)

After the bump, skim the [ubuntu-24.04 image
manifest](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md)
if your workflow leans on preinstalled tools: the 24.04 image ships
different default tool versions than 22.04 did.

## While you're in there: macos-14 dies sooner

`macos-14` (+ `-large`/`-xlarge`) is on a **shorter** countdown —
brownouts since July 6, 2026 and fully unsupported **November 2, 2026**
([#13518](https://github.com/actions/runner-images/issues/13518)).
D020 flags it too; the fix is by hand (`macos-15` or `macos-26` — newer
images change Xcode majors, so the target is your call).

---

*Generated by
[`scripts/gen-runner-countdown.py`](https://github.com/linnea-bakshi/gha-doctor/blob/main/scripts/gen-runner-countdown.py)
from a fresh top-250 sweep. See also: [rules reference](rules.md) ·
[state of the top 250](state-of-actions.md) ·
[the CI waste ledger](waste-study.md).*
""")
