#!/usr/bin/env python3
"""Render docs/img/coverage.svg from a merged Go cover profile.

Usage: go tool cover -func=merged.out | scripts/gen-coverage-badge.py > docs/img/coverage.svg

Reads the `total: ... NN.N%` line from stdin. Shields-flat-style badge,
no external services — the number comes from scripts/coverage.sh (unit +
integration binary coverage), regenerated by the weekly badge workflow
and gated in CI, so it cannot silently drift from reality.
"""
import sys

def color(pct: float) -> str:
    if pct >= 85: return "#4c1"       # brightgreen
    if pct >= 80: return "#97ca00"    # green
    if pct >= 70: return "#a4a61d"    # yellowgreen
    if pct >= 60: return "#dfb317"    # yellow
    return "#e05d44"                  # red

def main() -> None:
    pct = None
    for line in sys.stdin:
        if line.startswith("total:"):
            pct = float(line.strip().split()[-1].rstrip("%"))
    if pct is None:
        sys.exit("no 'total:' line on stdin (pipe `go tool cover -func=...`)")
    label, value = "coverage", f"{pct:.0f}%"
    # 6px padding + ~6.5px/char approximates shields' Verdana metrics.
    lw = 12 + int(6.5 * len(label))
    vw = 12 + int(6.5 * len(value))
    w = lw + vw
    svg = f"""<svg xmlns="http://www.w3.org/2000/svg" width="{w}" height="20" role="img" aria-label="{label}: {value}">
  <title>{label}: {value}</title>
  <linearGradient id="s" x2="0" y2="100%">
    <stop offset="0" stop-color="#bbb" stop-opacity=".1"/><stop offset="1" stop-opacity=".1"/>
  </linearGradient>
  <clipPath id="r"><rect width="{w}" height="20" rx="3" fill="#fff"/></clipPath>
  <g clip-path="url(#r)">
    <rect width="{lw}" height="20" fill="#555"/>
    <rect x="{lw}" width="{vw}" height="20" fill="{color(pct)}"/>
    <rect width="{w}" height="20" fill="url(#s)"/>
  </g>
  <g fill="#fff" text-anchor="middle" font-family="Verdana,Geneva,DejaVu Sans,sans-serif" font-size="11">
    <text x="{lw / 2}" y="14">{label}</text>
    <text x="{lw + vw / 2}" y="14">{value}</text>
  </g>
</svg>"""
    sys.stdout.write(svg + "\n")

if __name__ == "__main__":
    main()
